version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lsequeira"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rp5ceuqlte1e"
s3_prefix = "lsequeira"
region = "us-east-1"
profile = "lab-sys.admin_mfa"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "AppVPCCidr=\"10.0.0.0/16\" AppStage=\"dev\" AppInternetAccessCidr=\"189.0.124.125/32\" AppServerImageId=\"ami-02e8df324a09fe4a9\" AppBastionHostImageId=\"ami-03ededff12e34e59e\" AppBastionHostInstanceType=\"t2.micro\" AppServerInstanceType=\"t2.micro\" AppKeyName=\"lab-sysadmin\" AppSNSRecieverEmail=\"lucas.sequeira@datarain.com.br\" AppSSOARN=\"arn:aws:iam::685463979595:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_AdministratorAccess_69c5f967629e5ab5\""
image_repositories = []
